### ISSUE TITLE
Double join throwing error

### ISSUE THREAD

**Issue by Meldiron** [wwwouter/typed-knex#28]
**Issue type:**

[X] Question
[X] Bug report
[ ] Feature request
[ ] Documentation issue

**Database system/driver:**

[ ] Postgres
[X] MSSQL
[ ] MySQL
[ ] MariaDB
[ ] SQLite3
[ ] Oracle
[ ] Amazon Redshift

**typed-knex version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Description:**

Class configuration:
```
@Table('weapons')
export class TableWeapons {
  @Column({ name: 'id', primary: true })
  id: number;
  @Column({ name: 'skin_id' })
  skinId: TableSkins | null;
  @Column({ name: 'skin_id' })
  skinIdPlain: number;
  @Column({ name: 'stattrak' })
  stattrak: boolean;
  @Column({ name: 'souvenir' })
  souvenir: boolean;
  @Column({ name: 'wear' })
  wear: string;
  @Column({ name: 'price' })
  price: number;
  @Column({ name: 'image' })
  image: string;
  @Column({ name: 'big_image' })
  bigImage: string;
}

@Table('skins')
export class TableSkins {
  @Column({ name: 'id', primary: true })
  id: number;
  @Column({ name: 'name' })
  name: string;
  @Column({ name: 'average_price' })
  averagePrice: number | null;
  @Column({ name: 'rarity' })
  rarity: string;
  @Column({ name: 'rarity_color' })
  rarityColor: string;
}

@Table('inventories')
export class TableInventories {
  @Column({ name: 'id', primary: true })
  id: number;
  @Column({ name: 'weapon_id' })
  weaponId: TableWeapons | null;
  @Column({ name: 'weapon_id' })
  weaponIdPlain: number;
  @Column({ name: 'amount' })
  amount: number;
  @Column({ name: 'profile_id' })
  profileId: TableProfiles | null;
  @Column({ name: 'profile_id' })
  profileIdPlain: number;
}
```

My code:
```
const invItems = await SQLManager.typedKnex
      .query(TableInventories)
      .select((r) => [r.id, r.weaponIdPlain, r.amount])
      .innerJoinTableOnFunction('weapon', TableWeapons, (join) => {
        join.on(
          (c) => c.id,
          '=',
          (c) => c.weaponIdPlain
        );
      })
      .innerJoinTableOnFunction('skin', TableSkins, (join) => {
        join.on(
          (c) => c.id,
          '=',
          (c) => c.weapon.skinIdPlain
        );
      })
      .where((r) => r.profileIdPlain, profile.id)
      .orderBy((r) => r.skin.name, 'asc')
      .orderBy((r) => r.skin.averagePrice, 'asc')
      .limit(onePage)
      .offset(offset)
      .getMany();
```

Error:
```
  error Error: Cannot get column data. Did you set @Column() attribute on TableInventories.skin?
  error     at Object.getColumnInformation (/Users/meldiron/Desktop/csgoNest/Server/node_modules/@wwwouter/typed-knex/src/decorators.ts:146:15)
  error     at TypedQueryBuilder.getColumnNameWithoutAlias (/Users/meldiron/Desktop/csgoNest/Server/node_modules/@wwwouter/typed-knex/src/typedKnex.ts:2135:37)
  error     at TypedQueryBuilder.getColumnNameWithoutAliasFromFunctionOrString (/Users/meldiron/Desktop/csgoNest/Server/node_modules/@wwwouter/typed-knex/src/typedKnex.ts:2054:21)
  error     at TypedQueryBuilder.orderBy (/Users/meldiron/Desktop/csgoNest/Server/node_modules/@wwwouter/typed-knex/src/typedKnex.ts:1301:18)
  error     at getInventory (/Users/meldiron/Desktop/csgoNest/Server/src/api/services/UserService.ts:367:8)
  error     at Object.handleRequest (/Users/meldiron/Desktop/csgoNest/Server/src/api/helpers/utils.ts:9:17)
  error     at getInventory (/Users/meldiron/Desktop/csgoNest/Server/src/api/controllers/userCtrl.ts:56:3) +0ms
```

If I remove second join (and orderBy, because they use data from second join), it works fine.

EDIT: Actually, I think it is problem with orderBy because if I move the select method and remove orderBy, it works:
```
const invItems = await SQLManager.typedKnex
      .query(TableInventories)
      .innerJoinTableOnFunction('weapon', TableWeapons, (join) => {
        join.on(
          (c) => c.id,
          '=',
          (c) => c.weaponIdPlain
        );
      })
      .innerJoinTableOnFunction('skin', TableSkins, (join) => {
        join.on(
          (c) => c.id,
          '=',
          (c) => c.weapon.skinIdPlain
        );
      })
      .select((r) => [
        r.id,
        r.weaponIdPlain,
        r.amount,
        r.skin.name,
        r.skin.averagePrice,
      ])
      .where((r) => r.profileIdPlain, profile.id)
      .limit(onePage)
      .offset(offset)
      .getMany();
```

**Comment by wwwouter** [comment]
Can you try v3.0.1?
